### ISSUE TITLE
微信读书“写想法”功能导入问题

### ISSUE THREAD

**Issue by xiyan818** [mdzz2048/siyuan-plugin-weread#14]
# 在微信读书中，如果只“写想法”而不划线
如图1，**分子遗传学**没有划线，只是对**分子遗传学**写了想法
![image](https://github.com/mdzz2048/siyuan-plugin-weread/assets/44111611/2a3da3b2-505c-4e18-a9cf-7107a2d11ee5)
# 就会出现对应的“写想法”的字无法导入，只会导入自己写的想法的内容。
如图2，没有导入对应的**分子遗传学**，而只是导入了“写想法”的内容
![image](https://github.com/mdzz2048/siyuan-plugin-weread/assets/44111611/e963874f-ea9b-4777-8e86-0e2c3dfd84a5)
# 然后我在 obsidian 中试了一下，发现即使**只写想法**，而**不划线的话**，对于“写想法”的文字也是可以导入的
如图3，既导入了**分子遗传学**，又导入了“写想法”的内容
![image](https://github.com/mdzz2048/siyuan-plugin-weread/assets/44111611/2f9ed8ca-69cc-489f-9f88-297b8e40ceef)
# 如果能够支持对应的“写想法”的文字也可以导入就好了

**Comment by mdzz2048** [comment]
> 如图2，没有导入对应的**分子遗传学**，而只是导入了“写想法”的内容

“写想法”内容是否存在重复？

**Comment by xiyan818** [comment]
目前的问题是，如果仅仅“写想法“的话，对应位置的微信读书文字原文无法导入思源笔记。写的想法的内容是可以正常导入的。

## 比如，下面这张图，不会出现对应位置的原文（红色框部分）
> **古代美索不达米亚人很早就建立了城市，而且非常注重城市的建设。当时的巴比伦城有用石板铺成的宽阔马路，而且设有地下水道。新巴比伦城有三道城墙。主墙每隔44米就有一座塔楼，全城共有300多座塔楼。**

## 导入后只会出现写的想法的具体内容（绿色框部分）
> **美索不达米亚（亚拉姆语：ܒܝܬ ܢܗܪܝܢ‎，希腊语：Μεσοποταμία，）是古希腊对两河流域的称谓，μεσο意为中间，ποταμία为古希腊文中河阿拉伯语：بِلَاد ٱلرَّافِدَيْن‎流之意，转化成为的“（两条）河流中间的地方”。**

![image](https://github.com/mdzz2048/siyuan-plugin-weread/assets/44111611/027d7f7b-e17b-4c6a-bd17-e9c4bd9be033)
## 附：导入后的思源笔记图片
![image](https://github.com/mdzz2048/siyuan-plugin-weread/assets/44111611/4a03f897-9297-45c2-a83f-7e391d5fa0e5)
## 我也在 obsidian 中试了一下，发现 obsidian 是可以同时导入原文和对应的想法的
![image](https://github.com/mdzz2048/siyuan-plugin-weread/assets/44111611/522f08f3-5c03-47ed-8975-08a89e35bb97)

如果原文和”写想法“的内容能够同时导入的话，就能快速回忆起书的内容，有利于后期整理笔记。

**Comment by mdzz2048** [comment]
绿色框部分内容是否重复了两次？麻烦思源截图截全一些

**Comment by xiyan818** [comment]
绿色的部分没有重复，而是只出现了绿色部分，没有红色部分。
![image](https://github.com/mdzz2048/siyuan-plugin-weread/assets/44111611/79032f7b-4264-40dd-b6af-a1b9dab53f07)

**Comment by mdzz2048** [comment]
设置里的笔记模板是这样的吗？
![image](https://github.com/mdzz2048/siyuan-plugin-weread/assets/86549958/c1338a6d-2c67-4691-b4e4-85e54da2ab9c)

**Comment by xiyan818** [comment]
如果按照{{abstract}}{{content}}这样设置的话，就会出现重复两次的情况
![image](https://github.com/mdzz2048/siyuan-plugin-weread/assets/44111611/767b3698-a8f2-447c-a384-a3f9fce1c788)

![image](https://github.com/mdzz2048/siyuan-plugin-weread/assets/44111611/6df22ae2-a597-4993-bba6-3f865837f43a)

**Comment by mdzz2048** [comment]
需要导入标注内容和想法需要按下面这个设置。存在重复是 bug，已经修复了，等下版本更新

> 设置里的笔记模板是这样的吗？ ![image](https://user-images.githubusercontent.com/86549958/258647739-c1338a6d-2c67-4691-b4e4-85e54da2ab9c.png)

**Comment by xiyan818** [comment]
好的，好的。感谢解答。可以 close 了
