### ISSUE TITLE
新版ui太炫酷了

### ISSUE THREAD

**Issue by chenshinshi** [mdzz2048/siyuan-plugin-weread#16]
但作者有没有意向模仿下微信读书样式？
![image](https://github.com/mdzz2048/siyuan-plugin-weread/assets/125173405/6f50f445-f351-4222-b95a-c784aa33b93a)
比如像这样

**Comment by chenshinshi** [comment]
> 是需要微信读书的划线样式吗？

是想要微信读书的书摘样式w

**Comment by mdzz2048** [comment]
目前的样式是参考微信读书-笔记页面下的样式。把想法移到了下面。
阅读界面的书摘样式涉及到一些交互（比如删除、设置可见性之类的），暂时不考虑做了
![IMG_20230808_113630](https://github.com/mdzz2048/siyuan-plugin-weread/assets/86549958/fd5860c3-e8c5-4dd4-a12e-5f39ddf6495a)
