### ISSUE TITLE
请问导入书籍笔记后，如何自动同步标注和想法呢？

### ISSUE THREAD

**Issue by philaw111** [mdzz2048/siyuan-plugin-weread#2]

**Comment by xueshanqiu** [comment]
我是2.9.10版本，设置好之后，点击图标后没什么反应。。。

**Comment by mdzz2048** [comment]
> 我是2.9.10版本，设置好之后，点击图标后没什么反应。。。

点击图标失效是个 bug，下个版本修复

**Comment by mdzz2048** [comment]
https://github.com/mdzz2048/siyuan-plugin-weread/releases/tag/v1.0.4
