### ISSUE TITLE
{{markText}}能不能只是摘抄的文本而不包含">"

### ISSUE THREAD

**Issue by muhanstudio** [mdzz2048/siyuan-plugin-weread#24]
因为要自己出来纯文本内容，比如化线标注什么的，在外面套一层=={{markText}}=或者其他的样式，里面的自带的">"就会变成纯文本显示出来"> 你好"，破坏了整体性

**Comment by mdzz2048** [comment]
我下个版本加个 markRowText 字段吧，这个字段是纯文本，markText 还是保持原来的格式。

**Comment by mdzz2048** [comment]
问一下是只有标注需要原始文本还是想法、热门标注都需要原始文本？

**Comment by muhanstudio** [comment]
你好，其实我感觉最好都是纯文本，给用户更多的排版空间，如果感觉有些用户可能不太删除折腾，可以内置一个已经写好的模板，但是排版符号不应该污染到元素内部

**Comment by mdzz2048** [comment]
> 最好都是纯文本，给用户更多的排版空间，如果感觉有些用户可能不太擅长排版，希望上手即用，可以内置一个已经写好的模板，但是排版符号不应该污染到内容元素内部

目前 v1.2.3 的标注和热门标注都加上 markRowText 字段。想法那里 abstract 和 content 的特殊处理先保持不动了，之后重构的时候再考虑内置模板和可供自定义的变量分开。
