### ISSUE TITLE
导入报错

### ISSUE THREAD

**Issue by Chenm4** [mdzz2048/siyuan-plugin-weread#5]
![image](https://github.com/mdzz2048/siyuan-plugin-weread/assets/98648589/dc50c806-650c-422b-9e90-88fc86ef6eb6)
请问一下这个是什么原因？删除文档后重建索引也没有用，版本为2.9.1，文档虽然创建了但是里面的笔记都是空的

**Comment by mdzz2048** [comment]
试试更新插件到最新版本，删除所有文档后重建索引，设置面板这里设置成这样

![image](https://github.com/mdzz2048/siyuan-plugin-weread/assets/86549958/328d55b8-9d39-4484-9956-7b82b0d34233)

**Comment by Chenm4** [comment]
> 试试更新插件到最新版本，删除所有文档后重建索引，设置面板这里设置成这样
> 
> ![image](https://user-images.githubusercontent.com/86549958/246428149-328d55b8-9d39-4484-9956-7b82b0d34233.png)

可以了，是设置面板没有填正确，感谢感谢
（再多问一句这个好像不是按照章节顺序划分的，我记得ob的好像是按照章节划分的这个以后能优化吗）

**Comment by mdzz2048** [comment]
> 再多问一句这个好像不是按照章节顺序划分的，我记得ob的好像是按照章节划分的这个以后能优化吗）

README 里提了这个缺陷了，在第二条，之后会做按章节划分的功能的

**Comment by mdzz2048** [comment]
没问题的话我先关了，感谢反馈
